import { render, screen, fireEvent, cleanup } from "@testing-library/react";
import { describe, it, expect, vi, afterEach } from "vitest";
import { AssetForm } from "./AssetForm";

describe("AssetForm", () => {
  afterEach(() => {
    cleanup();
  });

  it("renders all fields correctly", () => {
    render(<AssetForm onSubmit={vi.fn()} />);

    expect(screen.getByLabelText(/Asset Name/i)).toBeDefined();
    expect(screen.getByLabelText("Serial Number (Optional)")).toBeDefined();
    expect(screen.getByLabelText(/Category/i)).toBeDefined();
    expect(screen.getByLabelText(/Value/i)).toBeDefined();
    expect(screen.getByLabelText(/Status/i)).toBeDefined();
    expect(screen.getByLabelText(/Purchase Date/i)).toBeDefined();
  });

  it("shows validation errors for invalid data", () => {
    render(<AssetForm onSubmit={vi.fn()} />);

    const submitBtn = screen.getByRole("button", { name: /Register Asset/i });

    // Submit empty form (Name is required, Value is required)
    // We need to clear defaults if any?
    // Name has no default. Value has no default.
    fireEvent.click(submitBtn);

    // Expect Zod errors
    expect(
      screen.getByText(/Name must be at least 3 characters/i),
    ).toBeDefined();
    expect(screen.getByText(/Value must be positive/i)).toBeDefined(); // Value is NaN or undefined
  });

  it("submits correct data when valid", () => {
    const handleSubmit = vi.fn();
    render(<AssetForm onSubmit={handleSubmit} />);

    // Fill Form
    fireEvent.change(screen.getByLabelText(/Asset Name/i), {
      target: { value: "Dell XPS" },
    });
    fireEvent.change(screen.getByLabelText(/Value/i), {
      target: { value: "1500" },
    });

    // Serial Number (Optional) - leave empty to test optionality
    // Category - default electronics
    // Status - default active
    // Date - default today

    fireEvent.click(screen.getByRole("button", { name: /Register Asset/i }));

    expect(handleSubmit).toHaveBeenCalledOnce();
    const data = handleSubmit.mock.calls[0][0];

    expect(data.name).toBe("Dell XPS");
    expect(data.value).toBe(1500);
    expect(data.status).toBe("active");
    expect(data.category).toBe("electronics");
    // ID should be generated by schema default?
    // Wait, Schema default runs when input is processed by parse.
    expect(data.id).toBeDefined();
    expect(typeof data.id).toBe("string");
  });
});
